package cl_modelos_pojos;
// Generated 12/03/2017 03:42:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoplanta generated by hbm2java
 */
public class Tipoplanta  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Set<Plantas> plantases = new HashSet<Plantas>(0);

    public Tipoplanta() {
    }

	
    public Tipoplanta(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Tipoplanta(String nombre, String descripcion, Set<Plantas> plantases) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.plantases = plantases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Plantas> getPlantases() {
        return this.plantases;
    }
    
    public void setPlantases(Set<Plantas> plantases) {
        this.plantases = plantases;
    }




}


